[package]
name = "aarm_evm"
version = "0.1.0"
edition = "2024"

[dependencies]
aarm_core = { git = "https://github.com/anoma/aarm-risc0.git", rev = "83407a216cd3f032b9ec5eb9d3fd8d2591513c32", package = "aarm_core" }
aarm = { git = "https://github.com/anoma/aarm-risc0.git", rev = "83407a216cd3f032b9ec5eb9d3fd8d2591513c32", package = "aarm" }
dotenv = "0.15"
alloy = { version = "0.12", features = ["full"] }
tokio = "1.44"
serde = { version = "1.0.197", default-features = false }
