[package]
name = "evm_protocol_adapter_bindings"
version = "0.1.0"
edition = "2024"

[dependencies]
arm_risc0 = { git = "https://github.com/anoma/arm-risc0.git", rev = "3ca1cd7fe4a27d7ecbd5945782d112a34586df84", package = "arm" }
dotenv = "0.15"
alloy = { version = "1.0.1", features = ["full"] }
tokio = "1.44"
serde = { version = "1.0.197", default-features = false }
serde_json = "1.0.97"
