name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  contracts:
    name: Contracts
    runs-on: ubuntu-latest
    env:
      FOUNDRY_PROFILE: ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          cache: true

      - name: Show Foundry version
        run: forge --version

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Show Bun version
        run: bun --version
        working-directory: ./contracts

      - name: Install Solhint
        run: bun install solhint
        working-directory: ./contracts

      - name: Run Solhint in `src`
        run: bunx --bun solhint --config .solhint.json 'src/**/*.sol'
        working-directory: ./contracts

      - name: Run Forge build
        run: forge build --sizes --ast
        working-directory: ./contracts

      - name: Run Forge tests
        run: forge test -vvv --gas-report
        env:
          API_KEY_INFURA: ${{ secrets.API_KEY_INFURA }}
          API_KEY_ALCHEMY: ${{ secrets.API_KEY_ALCHEMY }}
        working-directory: ./contracts

      - name: Upload Contract Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contract-artifacts
          path: ./contracts/out
